server:
  port: 8080
  # 한글 깨짐 문제 해결
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

#데이터베이스 접속 정보
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://118.131.111.158:13306/kakaoproject
    username: root
    password: password
  # 9강: h2 DB, 웹 콘솔 접근 허용
  h2:
    console:
      enabled: true
  # 15강: data.sql 작동 안함 오류 해결
  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format-sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 580524444939-miu11bn1u95k341r751piodkc0je5606.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

env:
  serviceKey:
    8YTAm5lTksn9PCq63yrvj0l7A%2BC5EwJKwmAYiY8eB1M73uL6T3lpEZ5ryMKdWIo0ryYHDMZlftf4eVmhpJGg3Q%3D%3D